# Generated by Django 3.2.12 on 2022-03-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='biglotto',
        ),
        migrations.DeleteModel(
            name='biglottoplus',
        ),
        migrations.DeleteModel(
            name='bingobingo',
        ),
        migrations.DeleteModel(
            name='fiveninethree',
        ),
        migrations.DeleteModel(
            name='fourstar',
        ),
        migrations.DeleteModel(
            name='fourtynine',
        ),
        migrations.DeleteModel(
            name='powerlotto',
        ),
        migrations.DeleteModel(
            name='thirtyeight',
        ),
        migrations.DeleteModel(
            name='thirtynine',
        ),
        migrations.DeleteModel(
            name='threestar',
        ),
    ]
